apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: dikshita.kalita@smail.th-koeln.de
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret used to store the account's private key.
      name: haproxy-issuer-account-key
    # Add a ACME HTTP01 challenge solver
    solvers:
    - http01:
        ingress: {}
