apiVersion: v1
kind: Service
metadata:
  name: hello1-k8s
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello1-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello1-k8s
  template:
    metadata:
      labels:
        app: hello1-k8s
    spec:
      containers:
      - name: hello1-k8s
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello Mr Leischner!
