
# howtos I used are
#  install k3s
#    https://k3s.io/

# curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik" sh -
- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /home/vagrant/k3sinstall.sh
    owner: vagrant
    group: vagrant
    mode: 0755
  register: k3s_script

- name: Execute k3s installation script
  ansible.builtin.shell: /home/vagrant/k3sinstall.sh
  when: k3s_script.changed

- name: Add alias k for kubectl
  lineinfile:
    path: /home/vagrant/.bashrc
    line: "alias k=kubectl"
    state: present

- name: Change file ownership of k3s.yaml so that kubectl can access it
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: vagrant
    group: vagrant
    mode: '0644'
  become: yes
  when: k3s_script.changed
