apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-dkrp2
  namespace: kube-system
spec:
  secretName: wildcard-dkrp2-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.dkrp2.xyz"
