apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dkdemo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
