apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  dkdemo
subjects:
- kind: User
  name: https://accounts.google.com/:demo
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dkdemo
  apiGroup: rbac.authorization.k8s.io
